# Generated by Django 5.1.6 on 2025-03-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_user_avatar_alter_course_image_alter_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='User/%Y/%m/'),
        ),
    ]
